coverage:
    ignore:
        - "src/components/canrawsender/gui"
        - "src/components/canrawview/gui"
        - "src/components/canrawfilter/gui"
        - "src/components/cansignaldata/gui"
        - "src/components/cansignalsender/gui"
        - "src/components/canload/canloadpainter.h"
        - "src/common/guiinterface"
        - "src/common/candbpainter.cpp"
        - "src/common/candbpainter.h"
        - "src/common/nodepainter.h"
        - "src/common/propertyfields.h"
        - "src/gui/main*"
        - "src/gui/subwindow.h"
        - "src/gui/projectconfig/flowviewwrapper.h"
        - "src/gui/projectconfig/flowviewwrapper.cpp"
        - "src/gui/projectconfig/dragwidget.h"
        - "src/gui/projectconfig/dragwidget.cpp"
        - "src/gui/projectconfig/canloadpainter.h"
        - "src/gui/projectconfig/pcinterface.h"
        - "src/gui/projectconfig/pcimpl.h"
        - ".*/tests/.*"
        - "tools"
