coverage:
    ignore:
        - "src/components/canrawsender/gui"
        - "src/components/canrawview/gui"
        - "src/gui"
        - "src/common/guiinterface"
        - "tests"
        - "tools"
        - "src/components/projectconfig/flowviewwrapper.h"
        - "src/components/projectconfig/flowviewwrapper.cpp"
        - "src/components/projectconfig/dragwidget.h"
        - "src/components/projectconfig/dragwidget.cpp"
        - "src/components/projectconfig/nodepainter.h"
        - "src/components/projectconfig/canloadpainter.h"
        - "src/components/projectconfig/pcinterface.h"
        - "src/components/projectconfig/pcimpl.h"

