# Package generation

set(CPACK_PACKAGE_DESCRIPTION "CANDevStudio - CAN simulation software")
set(CPACK_PACKAGE_VERSION_MAJOR "${VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${VERSION_MINOR}")
if(GIT_COMMIT_HASH)
    set(CPACK_PACKAGE_VERSION_PATCH ${GIT_COMMIT_HASH})
else()
    set(CPACK_PACKAGE_VERSION_PATCH "${VERSION_PATCH}")
endif()
set(CPACK_PACKAGE_VENDOR "Mobica")
set(CPACK_PACKAGE_CONTACT "remigiusz.kollataj@mobica.com")
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE)
include(CPack)
