var annotated_dup =
[
    [ "CanDevice", "class_can_device.html", "class_can_device" ],
    [ "CanDeviceDataIn", "class_can_device_data_in.html", "class_can_device_data_in" ],
    [ "CanDeviceDataOut", "class_can_device_data_out.html", "class_can_device_data_out" ],
    [ "CanDeviceInterface", "struct_can_device_interface.html", "struct_can_device_interface" ],
    [ "CanDeviceModel", "class_can_device_model.html", "class_can_device_model" ],
    [ "CanDevicePrivate", "class_can_device_private.html", "class_can_device_private" ],
    [ "CanDeviceQt", "struct_can_device_qt.html", "struct_can_device_qt" ],
    [ "CanFactoryInterface", "struct_can_factory_interface.html", "struct_can_factory_interface" ],
    [ "CanFactoryQt", "struct_can_factory_qt.html", "struct_can_factory_qt" ],
    [ "CanNodeDataModelVisitor", "class_can_node_data_model_visitor.html", "class_can_node_data_model_visitor" ],
    [ "CanRawSender", "class_can_raw_sender.html", "class_can_raw_sender" ],
    [ "CanRawSenderModel", "class_can_raw_sender_model.html", "class_can_raw_sender_model" ],
    [ "CanRawSenderPrivate", "class_can_raw_sender_private.html", "class_can_raw_sender_private" ],
    [ "CanRawView", "class_can_raw_view.html", "class_can_raw_view" ],
    [ "CanRawViewModel", "class_can_raw_view_model.html", "class_can_raw_view_model" ],
    [ "CanRawViewPrivate", "class_can_raw_view_private.html", "class_can_raw_view_private" ],
    [ "CDSWidget", "struct_c_d_s_widget.html", "struct_c_d_s_widget" ],
    [ "CheckBoxInterface", "struct_check_box_interface.html", "struct_check_box_interface" ],
    [ "CRSFactory", "struct_c_r_s_factory.html", "struct_c_r_s_factory" ],
    [ "CRSFactoryInterface", "struct_c_r_s_factory_interface.html", "struct_c_r_s_factory_interface" ],
    [ "CRSGui", "struct_c_r_s_gui.html", "struct_c_r_s_gui" ],
    [ "CRSGuiInterface", "struct_c_r_s_gui_interface.html", "struct_c_r_s_gui_interface" ],
    [ "Iterator", "class_iterator.html", "class_iterator" ],
    [ "LineEditInterface", "struct_line_edit_interface.html", "struct_line_edit_interface" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "NewLineManager", "class_new_line_manager.html", "class_new_line_manager" ],
    [ "NLMCheckBox", "struct_n_l_m_check_box.html", "struct_n_l_m_check_box" ],
    [ "NLMFactory", "struct_n_l_m_factory.html", "struct_n_l_m_factory" ],
    [ "NLMFactoryInterface", "struct_n_l_m_factory_interface.html", "struct_n_l_m_factory_interface" ],
    [ "NLMLineEdit", "struct_n_l_m_line_edit.html", "struct_n_l_m_line_edit" ],
    [ "NLMPushButton", "struct_n_l_m_push_button.html", "struct_n_l_m_push_button" ],
    [ "PushButtonInterface", "struct_push_button_interface.html", "struct_push_button_interface" ],
    [ "SubWindow", "struct_sub_window.html", "struct_sub_window" ],
    [ "UniqueFilterModel", "class_unique_filter_model.html", "class_unique_filter_model" ],
    [ "VisitableWith", "struct_visitable_with.html", "struct_visitable_with" ]
];